### PR TITLE
Enabled dark and light mode with switch for docs using docsify-darkli…

### PR DESCRIPTION
**Pull request by boopathikumar018**
Enabled dark and light mode with switch for docs using docsify-darklight-theme with redesigned search bar. For more customization [see here](https://boopathikumar018.github.io/docsify-darklight-theme)

**Light Mode :**

Before 

image

After

image

**Dark Mode :**

image

### CODE REVIEW

**Comment by greybax** [comment]
Hi @boopathikumar018 , thank you for PR. It's interesting feature. Just one thing which I would to improve is can we use instead of circle switch toggle like this?
image

**Comment by boopathikumar018** [comment]
Sure let me work on this an update the PR.

**Comment by boopathikumar018** [comment]
Sure let me work on this and update the PR.

**Comment by boopathikumar018** [comment]
I have add icons as requested and made public. Attached screenshot for your reference. For more customization [see here](https://boopathikumar018.github.io/docsify-darklight-theme)

**Light Mode**

image

**Dark Mode**

image

**Comment by greybax** [comment]
Thanks for PR @boopathikumar018! Looks good to me. Merged 👍

**Comment by boopathikumar018** [comment]
Thank you @greybax

**Pull request merged**
