### PR TITLE
Automatically Create Movies ratings with framework ready for the docs, tv shows

### PR DESCRIPTION
**Pull request by perkinsjr**
Fixes issue #23 with the following details:

I changed the layout for the Movies.md to group by .5 ratings. 

Each movie now has its own rating under the title. They are still in higher to lower order.

To add new movies we would just add a movie to the movies_prebuilt with :star: Matrix_Score under the title. Then in the storage.js we add the Matrix_Score  and the imdb title id to the object. 

Then run npm run build-movies and that will automatically go out and collect all the data and insert into the text file and then render a new md. 

The only change to make this work is to add your own api key into the code. { apiKey: "" in the movie_markdown_builder.js

Let me know what you would like changed etc.

### CODE REVIEW

**Comment by perkinsjr** [comment]
@greybax if this works for you... I will create the tv shows and documentary in the same format and then add movie / tv/ documentary badge counts that dynamically change when we add new movies

**Comment by greybax** [comment]
Looks pretty good, I like it! :) one thing can we avoid *.txt files? May be use .md instead of them. For example ‘movies_template.md’ will generate ‘movies.md’ ?

**Comment by perkinsjr** [comment]
Yes, originally I had it as .md files and then switch back... I will make that change and then add docs and tv shows over the next couple days. Then I will push up changes to this pull request.

**Comment by greybax** [comment]
@perkinsjr great!

**Comment by perkinsjr** [comment]
@greybax Everything is done for movies, tv shows and documentaries... Same idea just run
build-movies
build-tv-series 
build-documentary
also I moved the 'apikey to an env to make it easy to keep track of. 

It should be ready to merge. 

Cheers!

**Comment by greybax** [comment]
Will figure out with conflicts and will merge it soon! Thank you for your work!

**Comment by greybax** [comment]
*Merged* Thank you for contribution @perkinsjr! 🙌

**Pull request merged**
